server:
  port: 9090
  context-path: /mybatis-plus

spring:
  ##数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mybatis_plus?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

##mybatis-plus配置
mybatis-plus:


